HAI
    WAZZUP
        I HAS A x ITZ 10
        I HAS A y ITZ 14
    BUHBYE
    VISIBLE BOTH OF x AN y
    VISIBLE BOTH SAEM x AN y
    VISIBLE BOTH OF x AN y
    VISIBLE DIFFRINT x AN y

    VISIBLE BOTH SAEM BIGGR OF x AN y AN x
    VISIBLE BOTH SAEM x AN SMALLR OF x AN y
    VISIBLE DIFFRINT BIGGR OF x AN y AN x
    VISIBLE DIFFRINT x AN SMALLR OF x AN y

KTHXBYE